name: Refresh profile readme

on:
  schedule:
    # Run at 0 am every day
    - cron: '0 15 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Generate 3D contribution profile
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: conf/3d-contrib-settings.json

      - name: Move files
        run: |
          mkdir -p ./utils ./builds
          mv ./profile-3d-contrib/* ./utils/
          rm -rf ./profile-3d-contrib

      # - name: Download github-contrib-stats
      #   run: |
      #     curl -sSL --output /tmp/github-contrib-stats.tar.gz https://github.com/kmararia/github-contrib-stats/releases/latest/download/github-contrib-stats-x86_64-unknown-linux-gnu.tar.gz && \
      #     tar -xvf /tmp/github-contrib-stats.tar.gz -C /tmp && \
      #     chmod +x /tmp/github-contrib-stats

      # - name: Update contribution stats
      #   run: /tmp/github-contrib-stats -u ${{ github.repository_owner }} --update contribution.md
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Push utilities to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: refresh-profile
          build_dir: builds
          committer: "github-actions[kev-bot] <github-actions[kev-bot]@users.noreply.github.com>"
          author: "github-actions[kev-bot] <github-actions[kev-bot]@users.noreply.github.com>"
          commit_message: "refresh 3D profile utils"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

